version: "3.5"
services:
  web:
    image: myapp/restwsql:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
     - backend    
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sakila
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
  db:
    environment:
      MYSQL_DATABASE: sakila
      MYSQL_ROOT_PASSWORD: pass
    image: mysql:5
    restart: always
    ports:
     - "3306:3306"
    networks:
     - backend
networks:
  backend:
